/* Generated by Yosys 0.38+75 (git sha1 01d6c12af, gcc 9.4.0-1ubuntu1~20.04.2 -fPIC -Os) */

module vending_machine(clk, rst, in, out, change);
  wire [1:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire [1:0] _116_;
  wire _117_;
  output [1:0] change;
  reg [1:0] change;
  input clk;
  wire clk;
  input [1:0] in;
  wire [1:0] in;
  wire [2:0] n_state;
  output out;
  reg out;
  input rst;
  wire rst;
  sky130_fd_sc_hd__clkinv_1 _118_ (
    .A(_084_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__clkinv_1 _119_ (
    .A(_082_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__clkinv_1 _120_ (
    .A(_083_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nor2b_1 _121_ (
    .A(_115_),
    .B_N(_087_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand3b_1 _122_ (
    .A_N(_115_),
    .B(_086_),
    .C(_087_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _123_ (
    .A(_084_),
    .B(_085_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__o21bai_1 _124_ (
    .A1(_087_),
    .A2(_086_),
    .B1_N(_115_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__a32oi_1 _125_ (
    .A1(_084_),
    .A2(_085_),
    .A3(_094_),
    .B1(_091_),
    .B2(_086_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor3b_1 _126_ (
    .A(_115_),
    .B(_086_),
    .C_N(_087_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand3_1 _127_ (
    .A(_084_),
    .B(_085_),
    .C(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2b_1 _128_ (
    .A(_085_),
    .B_N(_084_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2_1 _129_ (
    .A(_094_),
    .B(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand3_1 _130_ (
    .A(_092_),
    .B(_096_),
    .C(_098_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor3b_1 _131_ (
    .A(_087_),
    .B(_115_),
    .C_N(_086_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand3_1 _132_ (
    .A(_084_),
    .B(_085_),
    .C(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand3_1 _133_ (
    .A(_088_),
    .B(_085_),
    .C(_094_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__o21ai_0 _134_ (
    .A1(_086_),
    .A2(_097_),
    .B1(_091_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand3_1 _135_ (
    .A(_100_),
    .B(_101_),
    .C(_102_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__o21ai_0 _136_ (
    .A1(_115_),
    .A2(_089_),
    .B1(_084_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__xnor2_1 _137_ (
    .A(_084_),
    .B(_085_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__a22o_1 _138_ (
    .A1(_085_),
    .A2(_099_),
    .B1(_104_),
    .B2(_095_),
    .X(_105_)
  );
  sky130_fd_sc_hd__o31ai_1 _139_ (
    .A1(_115_),
    .A2(_086_),
    .A3(_093_),
    .B1(_092_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nor2_1 _140_ (
    .A(_089_),
    .B(_095_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__a22o_1 _141_ (
    .A1(_103_),
    .A2(_105_),
    .B1(_106_),
    .B2(_107_),
    .X(_112_)
  );
  sky130_fd_sc_hd__o21ai_0 _142_ (
    .A1(_115_),
    .A2(_090_),
    .B1(_084_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a32o_1 _143_ (
    .A1(_099_),
    .A2(_104_),
    .A3(_108_),
    .B1(_106_),
    .B2(_083_),
    .X(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _144_ (
    .A(_097_),
    .B(_099_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__o221ai_1 _145_ (
    .A1(_088_),
    .A2(_111_),
    .B1(_095_),
    .B2(_099_),
    .C1(_085_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nand2_1 _146_ (
    .A(_109_),
    .B(_110_),
    .Y(_114_)
  );
  reg \n_state_reg[1] ;
  always @(posedge clk)
    \n_state_reg[1]  <= _000_[1];
  assign n_state[1] = \n_state_reg[1] ;
  always @(posedge clk)
    if (_001_) out <= _117_;
  always @(posedge clk)
    change[0] <= _116_[0];
  always @(posedge clk)
    change[1] <= _116_[1];
  reg \n_state_reg[2] ;
  always @(posedge clk)
    \n_state_reg[2]  <= _000_[0];
  assign n_state[2] = \n_state_reg[2] ;
  assign _087_ = n_state[2];
  assign _115_ = rst;
  assign _086_ = n_state[1];
  assign _084_ = in[0];
  assign _085_ = in[1];
  assign _001_ = _081_;
  assign _000_[0] = _079_;
  assign _000_[1] = _080_;
  assign _082_ = change[0];
  assign _116_[0] = _112_;
  assign _083_ = change[1];
  assign _116_[1] = _113_;
  assign _111_ = out;
  assign _117_ = _114_;
endmodule
